#!/usr/bin/env python3
"""SUPPORT_SOLVER_PLAN record: key AV metrics (Cullen-Dehnen host, Monaghan) for each support-solver variant, one panel
per metric, raw values, plus the full tables. Reads the result dirs below; writes docs/support_solver/{comparison.png,tables.md}.

    scripts/plot_supportSolverComparison.py
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / 'docs/support_solver'

#: (label, results dir for the none config, for the C&D config); Owen (old table) is M0e
VARIANTS = [
    ('Owen, old table (M0e)', 'results/av_M0e_baseline', 'results/av_M0e_baseline'),
    ('Owen, fixed table (M0g, default)', 'results/av_M0g_baseline', 'results/av_M0g_baseline'),
    ('min(Owen, h(rho)) [clamp always]', 'results/support_solver/av_minclamp_none', 'results/support_solver/av_minclamp_cullenDehnen2010'),
    ('Newton h(rho)', 'results/support_solver/av_newton_none', 'results/support_solver/av_newton_cullenDehnen2010'),
    ('Newton + perSide + Omega (C)', 'results/support_solver/av_C_none', 'results/support_solver/av_C_cullenDehnen2010'),
    ('Newton + perSide, no Omega', None, 'results/support_solver/av_Cnoomega_cullenDehnen2010'),
]
COLORS = ['#9a9a95', '#2a78d6', '#eb6834', '#1baf7a', '#eda100', '#e87ba4']   # validated categorical slots (gray = old ref)

PANELS = [  # (case, metric, title, better)
    ('sod', 'contactSpikeP', 'Sod contact P spike', 'lower'),
    ('sod', 'L1_vx', 'Sod L1(v_x)', 'lower'),
    ('linearWave', 'waveVelocityErr', 'linear wave velocity error', 'lower'),
    ('sedov', 'peakRhoRatio', 'Sedov 3D peak rho/rho0 (exact 4)', 'higher'),
    ('gresho', 'L1_vphi', 'Gresho L1(v_phi)', 'lower'),
    ('gresho', 'angularMomentumLoss', 'Gresho angular-momentum loss', 'lower'),
    ('kelvinHelmholtz', 'khAmplitudeAt1p5', 'KH amplitude t=1.5 (McNally 0.148)', 'higher'),
    ('sedov', 'energyDrift', 'Sedov energy drift', 'lower'),
]
TABLE_METRICS = [('sod', 'L1_vx'), ('sod', 'contactSpikeP'), ('sod', 'contactSpikeA'), ('sod2d', 'L1_vx'), ('sod3d', 'L1_vx'),
                 ('sedov', 'peakRhoRatio'), ('sedov', 'shockRadiusErr'), ('noh', 'postShockRhoErr'), ('gresho', 'L1_vphi'),
                 ('gresho', 'angularMomentumLoss'), ('yee', 'L1_speed'), ('linearWave', 'waveVelocityErr'),
                 ('kelvinHelmholtz', 'khAmplitudeAt1p5'), ('rayleighTaylor', 'mixingWidth'), ('sedov', 'energyDrift'),
                 ('kelvinHelmholtz', 'energyDrift')]


def load(d):
    if d is None or not (REPO / d / 'results.json').exists():
        return {}
    return {(r['config'], r['case']): r['metrics'] for r in json.load(open(REPO / d / 'results.json'))['records']}


def main():
    data = [(lab, load(dn), load(dc)) for lab, dn, dc in VARIANTS]
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.ticker import MaxNLocator
    fig, axes = plt.subplots(2, 4, figsize=(17, 7.5))
    for ax, (case, k, title, better) in zip(axes.flat, PANELS):
        labels, vals, cols = [], [], []
        for (lab, _, dc), c in zip(data, COLORS):
            v = dc.get(('cullenDehnen2010', case), {}).get(k)
            if v is None:
                continue
            labels.append(lab); vals.append(abs(v) if k == 'angularMomentumLoss' else v); cols.append(c)
        y = range(len(vals))[::-1]
        ax.barh(list(y), vals, color=cols, height=0.7, edgecolor='white', linewidth=2)
        for yi, v in zip(y, vals):
            ax.text(v, yi, f' {v:.3g}', va='center', fontsize=8, color='#333')
        ax.set_yticks(list(y)); ax.set_yticklabels(labels if ax in axes[:, 0] else [], fontsize=8)
        ax.set_title(f'{title}\n({better} is better)', fontsize=9)
        ax.spines[['top', 'right']].set_visible(False)
        ax.grid(axis='x', color='#e6e6e3', lw=0.6); ax.set_axisbelow(True)
        ax.set_xlim(0, max(vals) * 1.3)
        ax.xaxis.set_major_locator(MaxNLocator(4))
    fig.suptitle('Support-solver variants, Monaghan host + Cullen-Dehnen switch, AV report full profile (SUPPORT_SOLVER_PLAN, 2026-10-06)', fontsize=11)
    fig.tight_layout()
    fig.savefig(OUT / 'comparison.png', dpi=120)

    lines = ['# Support-solver variants: full metric tables', '',
             'Generated by `scripts/plot_supportSolverComparison.py` from the `results/` dirs named in its `VARIANTS`.',
             'Monaghan host, AV report full profile; final-time metrics. `-` = not run.', '']
    for cfg, idx in (('none', 1), ('cullenDehnen2010', 2)):
        lines += [f'## `{cfg}`' + (' (alpha fixed at 1)' if cfg == 'none' else ''), '',
                  '| case metric | ' + ' | '.join(lab for lab, *_ in data) + ' |', '|---|' + '---|' * len(data)]
        for case, k in TABLE_METRICS:
            row = []
            for d in data:
                v = d[idx].get((cfg, case), {}).get(k)
                row.append(f'{v:.4g}' if isinstance(v, (int, float)) else '-')
            lines.append(f'| {case} {k} | ' + ' | '.join(row) + ' |')
        lines.append('')
    (OUT / 'tables.md').write_text('\n'.join(lines))
    print('wrote', OUT / 'comparison.png', OUT / 'tables.md')


if __name__ == '__main__':
    main()
